#!/usr/bin/env python3
"""Turn MHCD2022's person bounding boxes into segmentation masks.

MHCD2022 ships **no segmentation masks at all** — only VOC XML / YOLO txt
boxes over five classes. Two things have to be fixed before it is usable:

1. **Class filter.** Only class 0 (person) is kept. Vehicles, tanks,
   aeroplanes and warships are discarded: this is a camouflaged *human*
   detector.

2. **Split repair.** The shipped ``validation`` folder is a strict subset of
   ``training`` (all 480 val images also appear in train). Training on the
   shipped folders would validate on training data. The real split is
   ``train = training - validation``.

Masks are then generated by prompting MobileSAM (or SAM2) with each person
box and unioning the results. Pseudo-labels are only worth having if they are
policed, so every mask goes through automatic QC and an image is accepted as a
positive **only when every one of its person boxes passes** — a half-labelled
two-person image would otherwise teach the model that a visible person is
background.

Example
-------
    python scripts/01_prepare_mhcd.py \\
        --src dataset/MHCD2022/Military-Camouflage-MHCD2022/MHCD2022ForYolo \\
        --out data/mhcd --sam-variant mobile_sam --device cuda
"""

from __future__ import annotations

import argparse
import base64
import csv
import io
import sys
from collections import Counter
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from chd.data.manifest import DatasetWriter, count_components, image_size, load_rgb  # noqa: E402

PERSON_CLASS = 0

SAM_CHECKPOINTS = {
    "mobile_sam": "mobile_sam.pt",
    "sam2_hiera_tiny": "sam2.1_t.pt",
    "sam2_hiera_small": "sam2.1_s.pt",
}


# ---------------------------------------------------------------------------
# splits & boxes
# ---------------------------------------------------------------------------


def repaired_splits(src: Path) -> dict[str, list[str]]:
    """Read the shipped folders and subtract the train/val leak.

    Returns stems per split, guaranteed pairwise disjoint.
    """
    shipped = {}
    for name in ("training", "validation", "testing"):
        folder = src / "images" / name
        if not folder.is_dir():
            raise SystemExit(f"expected {folder} — is --src pointing at MHCD2022ForYolo?")
        shipped[name] = {p.stem for p in folder.glob("*.jpg")}

    leak = shipped["training"] & shipped["validation"]
    splits = {
        "train": sorted(shipped["training"] - shipped["validation"]),
        "val": sorted(shipped["validation"]),
        "test": sorted(shipped["testing"]),
    }

    print(f"[split] shipped   train={len(shipped['training'])} "
          f"val={len(shipped['validation'])} test={len(shipped['testing'])}")
    print(f"[split] train/val overlap removed: {len(leak)} images")
    print(f"[split] repaired  train={len(splits['train'])} "
          f"val={len(splits['val'])} test={len(splits['test'])}")

    names = list(splits)
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            clash = set(splits[a]) & set(splits[b])
            if clash:
                raise SystemExit(f"{a}/{b} still overlap on {len(clash)} stems after repair")
    return splits


def find_label(src: Path, stem: str) -> Path | None:
    for folder in ("training", "validation", "testing"):
        path = src / "labels" / folder / f"{stem}.txt"
        if path.exists():
            return path
    return None


def person_boxes(label_path: Path, height: int, width: int) -> list[tuple[float, float, float, float]]:
    """YOLO ``cls cx cy w h`` (normalised) -> absolute xyxy, person only.

    Sizes come from the decoded JPEG rather than the XML, because some MHCD
    XML headers disagree with the image they describe.
    """
    boxes = []
    for line in label_path.read_text().splitlines():
        parts = line.split()
        if len(parts) < 5 or int(float(parts[0])) != PERSON_CLASS:
            continue
        cx, cy, bw, bh = (float(v) for v in parts[1:5])
        x1 = (cx - bw / 2) * width
        y1 = (cy - bh / 2) * height
        x2 = (cx + bw / 2) * width
        y2 = (cy + bh / 2) * height
        x1, y1 = max(0.0, x1), max(0.0, y1)
        x2, y2 = min(float(width), x2), min(float(height), y2)
        if x2 > x1 + 1 and y2 > y1 + 1:
            boxes.append((x1, y1, x2, y2))
    return boxes


# ---------------------------------------------------------------------------
# quality control
# ---------------------------------------------------------------------------


def clean_mask(mask: np.ndarray, speckle_frac: float) -> np.ndarray:
    """Drop speckle components and fill pinholes before QC.

    SAM box prompts return an essentially perfect blob plus a scatter of
    single-pixel noise — measured over 37 boxes, the largest component holds
    99.9% of the mask area at the median (98.5% at p10) yet the raw component
    count reaches 51. Counting components without cleaning first rejects good
    masks for cosmetic reasons, so speckle is removed here rather than
    penalised in ``qc_mask``.
    """
    solid = np.asarray(mask) > 0
    total = int(solid.sum())
    if total == 0:
        return solid

    labels, n = ndimage.label(solid, structure=np.ones((3, 3)))
    if n > 1:
        sizes = np.bincount(labels.ravel())
        sizes[0] = 0
        keep = np.flatnonzero(sizes >= max(1, speckle_frac * total))
        if keep.size == 0:  # everything is tiny: keep only the largest blob
            keep = np.array([int(sizes.argmax())])
        solid = np.isin(labels, keep)

    # Fill enclosed pinholes, but never a real gap (e.g. between an arm and
    # the torso), so only holes below the same speckle threshold are closed.
    filled = ndimage.binary_fill_holes(solid)
    holes = filled & ~solid
    if holes.any():
        hole_labels, hole_n = ndimage.label(holes, structure=np.ones((3, 3)))
        if hole_n:
            hole_sizes = np.bincount(hole_labels.ravel())
            # Label 0 is "not a hole" (the whole rest of the frame), not a
            # real hole component — it must never be eligible for `small`,
            # or every pixel outside the mask gets swept back in as "filled".
            small = np.flatnonzero(hole_sizes[1:] < speckle_frac * total) + 1
            solid = solid | np.isin(hole_labels, small)
    return solid


def qc_mask(
    mask: np.ndarray,
    box: tuple[float, float, float, float],
    args: argparse.Namespace,
) -> str | None:
    """Return a rejection reason, or ``None`` if the mask is acceptable."""
    h, w = mask.shape
    area = int(mask.sum())
    if area == 0:
        return "empty"

    x1, y1, x2, y2 = box
    box_area = (x2 - x1) * (y2 - y1)
    if box_area / (h * w) < args.qc_min_box_frac:
        return "box_too_small"

    pad_x, pad_y = (x2 - x1) * 0.05, (y2 - y1) * 0.05
    inside = np.zeros_like(mask, dtype=bool)
    inside[
        max(0, int(y1 - pad_y)): min(h, int(np.ceil(y2 + pad_y))),
        max(0, int(x1 - pad_x)): min(w, int(np.ceil(x2 + pad_x))),
    ] = True
    outside_frac = float((mask & ~inside).sum()) / area
    if outside_frac > args.qc_outside:
        return f"leaks_outside_box({outside_frac:.2f})"

    ratio = area / box_area
    if ratio < args.qc_area_min:
        return f"area_too_small({ratio:.2f})"
    if ratio > args.qc_area_max:
        return f"area_too_large({ratio:.2f})"

    components = count_components(mask)
    if components > args.qc_max_components:
        return f"fragmented({components})"
    return None


def to_bool_mask(raw: np.ndarray, height: int, width: int) -> np.ndarray:
    """Coerce a SAM mask to a boolean array at the original image size."""
    arr = np.asarray(raw)
    if arr.ndim == 3:
        arr = arr[0]
    arr = arr > 0.5
    if arr.shape != (height, width):
        zoom = (height / arr.shape[0], width / arr.shape[1])
        arr = ndimage.zoom(arr.astype(np.uint8), zoom, order=0) > 0
        arr = arr[:height, :width]
        if arr.shape != (height, width):  # pad if zoom rounded short
            padded = np.zeros((height, width), dtype=bool)
            padded[: arr.shape[0], : arr.shape[1]] = arr
            arr = padded
    return arr


# ---------------------------------------------------------------------------
# review report
# ---------------------------------------------------------------------------


def overlay_thumb(image: np.ndarray, mask: np.ndarray, boxes, width: int = 260) -> str:
    canvas = image.copy()
    solid = mask > 0
    if solid.any():
        canvas[solid] = (0.45 * canvas[solid] + 0.55 * np.array([60, 255, 120])).astype(np.uint8)
    for x1, y1, x2, y2 in boxes:
        x1, y1, x2, y2 = int(x1), int(y1), int(min(x2, image.shape[1] - 1)), int(min(y2, image.shape[0] - 1))
        canvas[y1:y1 + 2, x1:x2] = [255, 220, 0]
        canvas[max(0, y2 - 2):y2, x1:x2] = [255, 220, 0]
        canvas[y1:y2, x1:x1 + 2] = [255, 220, 0]
        canvas[y1:y2, max(0, x2 - 2):x2] = [255, 220, 0]

    thumb = Image.fromarray(canvas)
    thumb.thumbnail((width, width))
    buffer = io.BytesIO()
    thumb.convert("RGB").save(buffer, format="JPEG", quality=72)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


_REVIEW_TEMPLATE = """<!doctype html>
<meta charset="utf-8"><title>MHCD SAM pseudo-mask review</title>
<style>
 body{font:14px/1.45 system-ui,sans-serif;margin:0;background:#111;color:#eee}
 header{position:sticky;top:0;background:#1b1b1b;padding:12px 18px;border-bottom:1px solid #333;z-index:9}
 h2{padding:14px 18px 0;margin:0;font-size:16px}
 .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:10px;padding:14px}
 .card{background:#1c1c1c;border:2px solid #333;border-radius:8px;padding:6px}
 .card.bad{border-color:#d9534f}
 .card img{width:100%;display:block;border-radius:4px}
 .meta{font-size:11px;color:#aaa;display:block;margin-top:4px}
 code{color:#ffb347}
</style>
<header><b>MHCD2022 &rarr; SAM person masks</b> &nbsp; __SUMMARY__</header>
<h2>Accepted (random sample)</h2>
<div class="grid">__ACCEPTED__</div>
<h2>Rejected (all)</h2>
<div class="grid">__REJECTED__</div>
"""


# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", type=Path,
                        default=Path("dataset/MHCD2022/Military-Camouflage-MHCD2022/MHCD2022ForYolo"))
    parser.add_argument("--out", type=Path, default=Path("data/mhcd"))
    parser.add_argument("--classes", type=int, nargs="+", default=[PERSON_CLASS],
                        help="YOLO class ids to keep (default: 0 = person)")
    parser.add_argument("--sam-variant", default="mobile_sam", choices=sorted(SAM_CHECKPOINTS))
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--qc-outside", type=float, default=0.10)
    parser.add_argument("--qc-area-min", type=float, default=0.05)
    parser.add_argument("--qc-area-max", type=float, default=0.95)
    parser.add_argument("--qc-max-components", type=int, default=3)
    parser.add_argument("--qc-min-box-frac", type=float, default=0.0005)
    parser.add_argument("--qc-speckle-frac", type=float, default=0.01,
                        help="drop mask components smaller than this fraction of mask area")
    parser.add_argument("--partial-policy", choices=("drop", "keep"), default="drop",
                        help="what to do when only some person boxes in an image pass QC")
    parser.add_argument("--review-html", type=Path, default=Path("reports/mhcd_sam_review.html"))
    parser.add_argument("--review-samples", type=int, default=200)
    parser.add_argument("--limit", type=int, help="process only the first N images (dry run)")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.classes != [PERSON_CLASS]:
        print(f"[warn] --classes {args.classes} keeps non-person objects; "
              "the combined model is human-only by design")

    splits = repaired_splits(args.src)
    if args.limit:
        splits = {k: v[: max(1, args.limit // 3)] for k, v in splits.items()}

    from ultralytics import SAM

    sam = SAM(SAM_CHECKPOINTS[args.sam_variant])

    writer = DatasetWriter(args.out, "mhcd", overwrite=args.overwrite)
    qc_rows: list[dict] = []
    accepted_cards: list[str] = []
    rejected_cards: list[str] = []
    tally = Counter()
    rng = np.random.default_rng(args.seed)

    work = [(stem, split) for split, stems in splits.items() for stem in stems]
    work.sort()

    for stem, split in tqdm(work, desc=f"SAM({args.sam_variant})", unit="img"):
        image_path = next(
            (p for p in (args.src / "images" / d / f"{stem}.jpg"
                         for d in ("training", "validation", "testing")) if p.exists()),
            None,
        )
        if image_path is None:
            tally["missing_image"] += 1
            continue

        height, width = image_size(image_path)
        label_path = find_label(args.src, stem)
        boxes = []
        if label_path is not None:
            boxes = person_boxes(label_path, height, width)

        # No person at all -> a genuine presence-gate negative.
        if not boxes:
            tally["negative"] += 1
            if not (writer.has(stem) and not args.overwrite):
                writer.add(
                    stem=stem, split=split, image_src=image_path,
                    mask=np.zeros((height, width), dtype=np.uint8),
                    source="mhcd", extra="no_person", is_negative=True,
                )
            continue

        results = sam(str(image_path), bboxes=[list(b) for b in boxes],
                      device=args.device, verbose=False)
        raw_masks = results[0].masks
        if raw_masks is None or len(raw_masks.data) != len(boxes):
            tally["sam_failed"] += 1
            qc_rows.append({"stem": stem, "split": split, "box": -1,
                            "verdict": "reject", "reason": "sam_no_output"})
            continue

        per_box, reasons = [], []
        for index, (raw, box) in enumerate(zip(raw_masks.data.cpu().numpy(), boxes, strict=True)):
            mask = clean_mask(to_bool_mask(raw, height, width), args.qc_speckle_frac)
            reason = qc_mask(mask, box, args)
            qc_rows.append({
                "stem": stem, "split": split, "box": index,
                "verdict": "accept" if reason is None else "reject",
                "reason": reason or "",
            })
            if reason is None:
                per_box.append(mask)
            else:
                reasons.append(reason)
                tally[f"reject:{reason.split('(')[0]}"] += 1

        complete = len(per_box) == len(boxes)
        usable = per_box and (complete or args.partial_policy == "keep")

        if not usable:
            tally["image_dropped"] += 1
            if len(rejected_cards) < 400:
                image = load_rgb(image_path)
                union = np.logical_or.reduce(per_box) if per_box else np.zeros((height, width), bool)
                rejected_cards.append(
                    f'<div class="card bad"><img src="data:image/jpeg;base64,'
                    f'{overlay_thumb(image, union, boxes)}"><span class="meta">{stem} '
                    f'&middot; {len(per_box)}/{len(boxes)} boxes passed<br>'
                    f'<code>{"; ".join(reasons) or "all rejected"}</code></span></div>'
                )
            continue

        union = np.logical_or.reduce(per_box).astype(np.uint8) * 255
        tally["accepted"] += 1
        if not (writer.has(stem) and not args.overwrite):
            writer.add(
                stem=stem, split=split, image_src=image_path, mask=union, source="mhcd",
                extra=f"boxes={len(boxes)};partial={int(not complete)}",
            )
        if len(accepted_cards) < args.review_samples and rng.random() < 0.15:
            accepted_cards.append(
                f'<div class="card"><img src="data:image/jpeg;base64,'
                f'{overlay_thumb(load_rgb(image_path), union, boxes)}">'
                f'<span class="meta">{stem} &middot; {len(boxes)} box(es) &middot; '
                f'fg {union.astype(bool).mean():.3f}</span></div>'
            )

    summary = writer.finalize()

    args.out.mkdir(parents=True, exist_ok=True)
    with (args.out / "sam_qc.csv").open("w", newline="") as fh:
        qc_writer = csv.DictWriter(fh, fieldnames=["stem", "split", "box", "verdict", "reason"])
        qc_writer.writeheader()
        qc_writer.writerows(qc_rows)

    box_accept = sum(r["verdict"] == "accept" for r in qc_rows)
    box_total = sum(r["box"] >= 0 for r in qc_rows)
    box_rate = box_accept / box_total if box_total else 0.0
    person_images = tally["accepted"] + tally["image_dropped"]
    image_rate = tally["accepted"] / person_images if person_images else 0.0

    headline = (
        f"boxes {box_accept}/{box_total} ({box_rate:.1%}) &middot; "
        f"person-images {tally['accepted']}/{person_images} ({image_rate:.1%}) &middot; "
        f"negatives {tally['negative']}"
    )
    args.review_html.parent.mkdir(parents=True, exist_ok=True)
    args.review_html.write_text(
        _REVIEW_TEMPLATE.replace("__SUMMARY__", headline)
        .replace("__ACCEPTED__", "\n".join(accepted_cards) or "<p>none</p>")
        .replace("__REJECTED__", "\n".join(rejected_cards) or "<p>none</p>")
    )

    print("\n" + "=" * 62)
    print(f"  box accept rate    : {box_accept}/{box_total} = {box_rate:.1%}")
    print(f"  image accept rate  : {tally['accepted']}/{person_images} = {image_rate:.1%}")
    print(f"  presence negatives : {tally['negative']} (images with no person)")
    for reason, n in sorted(tally.items()):
        if reason.startswith("reject:"):
            print(f"    {reason[7:]:<22} {n}")
    print(f"  dataset            : {summary}")
    print(f"  qc log             : {args.out / 'sam_qc.csv'}")
    print(f"  review             : {args.review_html}")
    print("=" * 62)
    if image_rate < 0.70:
        print("\n!! accept rate below 70% — recommend demoting MHCD to eval-only")
        print("!! rather than training on unreliable pseudo-masks.")


if __name__ == "__main__":
    main()
